//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class w_admin
    {
        public int id { get; set; }
        [DisplayName("Account")]
        public string username { get; set; }
        [DisplayName("Password")]
        public string password { get; set; }
        [DisplayName("Admin Name")]
        public string nickname { get; set; }
        [DisplayName("Permission")]
        public int permission { get; set; }
        [DisplayName("Create Time")]
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
