//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_buildings
    {
        public int id { get; set; }
        public string address { get; set; }
        public string type { get; set; }
        public string owner { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int rooms { get; set; }
        public string building_area { get; set; }
        public string land_area { get; set; }
    }
}
